{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nexus.fullname" . }}
  namespace: {{ include "nexus.namespace" . }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "nexus.selectorLabels" . | nindent 6 }}
  unhealthyPodEvictionPolicy: IfHealthyBudget
{{- end }}

