apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: simple-app
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - stratus
  selector:
    matchLabels:
      app: simple-app
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s

